# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
        echo abc > ravi.txt
        echo pqr > jaswant.txt
        zip hiscox.zip *
        mkdir hiscox && cp hiscox.zip hiscox/
        cd hiscox
     
        
  displayName: 'Run a multi-line script'
